### ISSUE TITLE
Design documents, tools, procedures, examples, have the old license

### ISSUE THREAD

**Issue by gareth-rees** [Ravenbrook/mps#26]
The source code has the new 2-clause BSD-like license, but the design documents, tools, procedures, examples and Makefiles have the old 3-clause GPL-like license. These files should be updated to the new license (unless this is deliberate in some way).

While we're modifying the license, it should say
```
Copyright (C) 2001-2020 Ravenbrook Limited <https://www.ravenbrook.com/>.
```
using the https version of the URL.

Also, the license in design/guide.impl.c.format.txt is not discarded when making the manual -- this is because the source says "History" rather than "Document History"

**Comment by UNAA008** [comment]
I may already have addressed some of this in the licence branch which I haven't yet fully merged into the mainline.  I'll check and update this issue accordingly.

**Comment by gareth-rees** [comment]
If you can push your changes then I'll rebase on them and see if anything was missed.

**Comment by UNAA008** [comment]
Done in change 197111.

**Comment by gareth-rees** [comment]
Ok, I've rebased pull request #27 on your changes — I only found just a couple of files you missed, but I made a few more license-related changes.
